spring.application.name=main

aws.region=ap-south-1

aws.dynamodb.table=StudentTable

spring.datasource.url=jdbc:postgresql://${AURORA_ENDPOINT}:5432/studentdb
spring.datasource.username=admin
spring.datasource.password=StudentDb123!
spring.datasource.driver-class-name=org.postgresql.Driver

aws.elasticache.endpoint=${ELASTICACHE_ENDPOINT}
aws.elasticache.port=${ELASTICACHE_PORT}

aws.memorydb.endpoint=${MEMORYDB_ENDPOINT}
aws.memorydb.port=${MEMORYDB_PORT}